service: yt-synch-db

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs12.x

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'