name: build
on: [pull_request, push]

jobs:
  build_ubuntu:
    name: Ubuntu Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: checks
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: yarn pack test
        run: |
          yarn pack pack --filename youtube-synch-test.tgz
          tar zxvf ./youtube-synch-test.tgz -C youtube-synch
          cd ./youtube-synch/package && yarn link

  cli_build_osx:
    name: MacOS Checks
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: checks
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: yarn pack test
        run: |
          yarn pack pack --filename youtube-synch-test.tgz
          tar zxvf ./youtube-synch-test.tgz -C youtube-synch
          cd ./youtube-synch/package && yarn link
