name: build
on: [pull_request, push]

jobs:
  build_ubuntu:
    name: Ubuntu Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: checks
        run: |
          npm install --frozen-lockfile
          npm run build
      - name: npm pack test
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          npm pack
          tar zxvf ./youtube-sync-${PACKAGE_VERSION}.tgz
          cd ./package && npm link

  build_osx:
    name: MacOS Checks
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: checks
        run: |
          npm install --frozen-lockfile
          npm run build
      - name: npm pack test
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          npm pack
          tar zxvf ./youtube-sync-${PACKAGE_VERSION}.tgz
          cd ./package && npm link
